version: '3.7'

services:
  telegram_bot:
    build:
      context: .
    container_name: telegram_bot
    env_file:
      - .env
    networks:
      - dev
    depends_on:
      - telegram_postgres

  telegram_postgres:
    image: postgres:12.2-alpine
    container_name: postgres
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
    ports:
      - "5435:5432"
    networks:
      - dev
    volumes:
      - postgres_data:/var/lib/postgresql/data


volumes:
  postgres_data:

networks:
  dev: